# Generated by Django 5.1.2 on 2024-10-25 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_subscription_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("basic", "Basic Permission"),
                    ("pro", "Pro Permission"),
                    ("adbanced", "Advanced Permission"),
                    ("basic_ai", "Basic AI Subscription"),
                ]
            },
        ),
    ]
