# Generated by Django 5.1.2 on 2024-10-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0010_subscriptionprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprice",
            name="price",
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
        ),
    ]
