# Generated by Django 5.1.2 on 2024-10-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_alter_subscriptionprice_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(default=-1),
        ),
    ]
