# Generated by Django 5.1.2 on 2024-10-27 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0013_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["order", "featured", "-updated"],
                "permissions": [
                    ("basic", "Basic Permission"),
                    ("pro", "Pro Permission"),
                    ("adbanced", "Advanced Permission"),
                    ("basic_ai", "Basic AI Permission"),
                ],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="featured",
            field=models.BooleanField(
                default=True, help_text="Featured on Django pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Ordering on Django pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
