# Generated by Django 5.1.2 on 2024-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0015_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True,
                help_text=" Benefits of a plan, separated by new line",
                null=True,
            ),
        ),
    ]
