# Generated by Django 5.1.2 on 2024-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0016_subscription_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="description",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
