# Generated by Django 5.1.2 on 2024-10-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_subscription_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
