# Generated by Django 5.1.2 on 2024-10-27 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0018_usersubscription_stripe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="stripe_id",
            new_name="sub_stripe_id",
        ),
    ]
