name: 1 - Hello World GitHub Actions

on: # when to run
  workflow_dispatch: # to enable manual re-runs
  # schedule: 
  #   - cron: '30 15 * * *' # everyday at 15:30
  # push: #git push
  #   branch:
  #     - main

jobs: # what to run
  hello: # first job
    runs-on: ubuntu-latest # where to run
    steps:
      - name: Hello there
        run: echo "Hello!"