name: 2 - Test Django Basic

on: 
  workflow_dispatch: 
  push: 
    branch:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest 
    env: 
      DJANGO_DEBUG: 0 
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
      NEON_GH_BRANCH: 'gh-delete'
      NEON_DEV_BRANCH: 'dev' # usually would be prod, but using dev bc main was not synced to it
    steps:
      - name: Chechout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'

      - name: Install Neon CLI
        run: |
          npm install -g neonctl
      
      - name: Delete previous branch
        continue-on-error: true
        run: |
          neonctl branches delete "${{ env.NEON_GH_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"

      - name: Create new GH Actions branch  
        run: |
          neonctl branches create --name "${{ env.NEON_GH_BRANCH }}" --parent "${{ env.NEON_DEV_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"

      - name: Database URL Env Value for new GH Actions branch  
        run: |
          MY_NEON_CONNECTION_STRING = $(neonctl connection-string --branch "${{ env.NEON_GH_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}")
          echo "DATABASE_URL=$MY_NEON_CONNECTION_STRING" >> $GITHUB_ENV

      - name: Setup Django Secret Key
        run: |
          MY_GEN_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >> $GITHUB_ENV

      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt

      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test

