name: 4 - Scheduled Production Worker

on: 
  workflow_dispatch: 
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 4 1 * *'

jobs: 
  test:
    runs-on: ubuntu-latest 
    env: 
      DJANGO_DEBUG: 0 
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
      NEON_DEV_BRANCH: 'dev' # usually would be prod, but using dev bc main was not synced to it
    steps:
      - name: Chechout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'

      - name: Install Neon CLI
        run: |
          npm install -g neonctl

      - name: Database URL Env Value for new GH Actions branch  
        run: |
          MY_NEON_CONNECTION_STRING=$(neonctl connection-string --branch "${{ env.NEON_DEV_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}")
          echo "DATABASE_URL=$MY_NEON_CONNECTION_STRING" >> $GITHUB_ENV

      - name: Setup Django Secret Key
        run: |
          MY_GEN_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >> $GITHUB_ENV

      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt

      - name: Django Migrate Database
        working-directory: ./src
        run: |
          python manage.py migrate

      - name: Django Users Sync Stripe Subs
        working-directory: ./src
        if: github.event.schedule != '0 4 1 * *'
        run: |
          python manage.py sync_user_subs --day-start 0 --day-end 1 --sync-active #today and tomorrow
        
      - name: Clear Dangling Stripe Subs
        working-directory: ./src
        if: github.event.schedule == '0 4 1 * *'
        run: |
          python manage.py sync_user_subs --clear-dangling

